import course1 from "../assets/Course1.webp";
import course2 from "../assets/Course 2.jpeg";
import course3 from "../assets/Course3.jpeg";
import course4 from "../assets/course4.png";
import course5 from "../assets/course5.jpg";
import course6 from "../assets/course6.jpeg";
import course7 from "../assets/course7.jpeg";
import course8 from "../assets/course8.webp";
import course9 from "../assets/course9.jpeg";
import course10 from "../assets/course10.jpeg";
import course11 from "../assets/course11.jpeg";
import course12 from "../assets/course12.jpeg";
import course13 from "../assets/course13.jpeg";
import course14 from "../assets/course14.jpeg";
import course15 from "../assets/course15.jpeg";

const courseData = [
  {
    id: 1,
    title: "Complete React Bootcamp",
    image: course1,
    price: "$49",
    lessons: 20,
    duration: "15h",
    instructor: "John Doe",
    instructorEmail: "john@mentorcraft.com",
    rating: 4.8,
    category: "Development",
  },
  {
    id: 2,
    title: "UI/UX Design Fundamentals",
    image: course2,
    price: "$39",
    lessons: 12,
    duration: "10h",
    instructor: "Fatima Rizvi",
    instructorEmail: "fatima@mentorcraft.com",
    rating: 4.6,
    category: "Design",
  },
  {
    id: 3,
    title: "Python for Data Science",
    image: course3,
    price: "$59",
    lessons: 18,
    duration: "14h",
    instructor: "Ali Murtaza",
    instructorEmail: "ali@mentorcraft.com",
    rating: 4.7,
    category: "Development",
  },
  {
    id: 4,
    title: "Digital Marketing Mastery",
    image: course4,
    price: "$29",
    lessons: 10,
    duration: "8h",
    instructor: "Sara Ahmed",
    instructorEmail: "sara@mentorcraft.com",
    rating: 4.5,
    category: "Marketing",
  },
  {
    id: 5,
    title: "Adobe Illustrator Essentials",
    image: course5,
    price: "$35",
    lessons: 15,
    duration: "9h",
    instructor: "Zainab Malik",
    instructorEmail: "zainab@mentorcraft.com",
    rating: 4.3,
    category: "Design",
  },
  {
    id: 6,
    title: "Machine Learning A-Z",
    image: course6,
    price: "$65",
    lessons: 22,
    duration: "18h",
    instructor: "Omar Farooq",
    instructorEmail: "omar@mentorcraft.com",
    rating: 4.9,
    category: "AI",
  },
  {
    id: 7,
    title: "WordPress Website Creation",
    image: course7,
    price: "$25",
    lessons: 8,
    duration: "6h",
    instructor: "Ayesha Rehman",
    instructorEmail: "ayesha@mentorcraft.com",
    rating: 4.4,
    category: "Development",
  },
  {
    id: 8,
    title: "Excel for Beginners",
    image: course8,
    price: "Free",
    lessons: 6,
    duration: "4h",
    instructor: "Imran Qureshi",
    instructorEmail: "imran@mentorcraft.com",
    rating: 4.1,
    category: "Business",
  },
  {
    id: 9,
    title: "Advanced Figma Design",
    image: course9,
    price: "$42",
    lessons: 14,
    duration: "11h",
    instructor: "Nida Khan",
    instructorEmail: "nida@mentorcraft.com",
    rating: 4.6,
    category: "Design",
  },
  {
    id: 10,
    title: "YouTube Content Strategy",
    image: course10,
    price: "$30",
    lessons: 11,
    duration: "7h",
    instructor: "Talha Naeem",
    instructorEmail: "talha@mentorcraft.com",
    rating: 4.2,
    category: "Marketing",
  },
  {
    id: 11,
    title: "JavaScript for Beginners",
    image: course11,
    price: "$35",
    lessons: 16,
    duration: "12h",
    instructor: "Kiran Fatima",
    instructorEmail: "kiran@mentorcraft.com",
    rating: 4.5,
    category: "Development",
  },
  {
    id: 12,
    title: "Intro to Cloud Computing",
    image: course12,
    price: "$48",
    lessons: 17,
    duration: "13h",
    instructor: "Bilal Arshad",
    instructorEmail: "bilal@mentorcraft.com",
    rating: 4.7,
    category: "IT",
  },
  {
    id: 13,
    title: "SEO Optimization Basics",
    image: course13,
    price: "$27",
    lessons: 9,
    duration: "6h",
    instructor: "Maria Asif",
    instructorEmail: "maria@mentorcraft.com",
    rating: 4.3,
    category: "Marketing",
  },
  {
    id: 14,
    title: "Flutter App Development",
    image: course14,
    price: "$55",
    lessons: 19,
    duration: "14h",
    instructor: "Hassan Raza",
    instructorEmail: "hassan@mentorcraft.com",
    rating: 4.6,
    category: "Development",
  },
  {
    id: 15,
    title: "Public Speaking Masterclass",
    image: course15,
    price: "$33",
    lessons: 13,
    duration: "9h",
    instructor: "Nimra Shah",
    instructorEmail: "nimra@mentorcraft.com",
    rating: 4.4,
    category: "Business",
  },
{
  id: 16,
  title: "Advanced React Patterns",
  image: course3,
  price: "$59",
  lessons: 15,
  duration: "12h",
  instructor: "John Doe",
  rating: 4.7,
  category: "Development",
},
{
  id: 17,
  title: "Frontend Performance Optimization",
  image: course7,
  price: "$45",
  lessons: 11,
  duration: "8h",
  instructor: "John Doe",
  rating: 4.6,
  category: "Development",
},
{
  id: 18,
  title: "React with TypeScript",
  image: course6,
  price: "$49",
  lessons: 16,
  duration: "10h",
  instructor: "John Doe",
  rating: 4.8,
  category: "Development",
},

];

export default courseData;
