const instructorData = {
  "John Doe": {
    name: "John Doe",
    email: "john@mentorcraft.com",
    phone: "123-456-7890",
    website: "https://johndoe.dev",
    bio: "Senior React Developer & Mentor at Mentor Craft. Passionate about frontend performance and modern UI patterns.",
    image: "", // Add base64 string if needed
  },
  "Fatima Rizvi": {
    name: "Fatima Rizvi",
    email: "fatima@mentorcraft.com",
    phone: "987-654-3210",
    website: "https://fatimadesigns.com",
    bio: "UI/UX expert with 8+ years of design experience and strong focus on usability.",
    image: "",
  },
  "Ali Murtaza": {
    name: "Ali Murtaza",
    email: "ali@mentorcraft.com",
    phone: "333-888-1111",
    website: "https://alimurtaza.tech",
    bio: "Data Scientist & Python enthusiast with real-world experience in AI & ML models.",
    image: "",
  },
  "Sara Ahmed": {
    name: "Sara Ahmed",
    email: "sara@mentorcraft.com",
    phone: "456-789-0123",
    website: "https://saramarkets.com",
    bio: "Digital Marketing Guru, SEO wizard & social media growth strategist.",
    image: "",
  },
  "Zainab Malik": {
    name: "Zainab Malik",
    email: "zainab@mentorcraft.com",
    phone: "111-222-3333",
    website: "https://zainabdesigns.com",
    bio: "Creative Illustrator & branding expert, teaching Illustrator like a pro!",
    image: "",
  },
  "Omar Farooq": {
    name: "Omar Farooq",
    email: "omar@mentorcraft.com",
    phone: "777-444-8888",
    website: "https://omar-ai.net",
    bio: "AI Engineer & Machine Learning Instructor with industry-grade models under his belt.",
    image: "",
  },
  "Ayesha Rehman": {
    name: "Ayesha Rehman",
    email: "ayesha@mentorcraft.com",
    phone: "555-666-7777",
    website: "https://ayesharehman.dev",
    bio: "WordPress developer helping small businesses build fast websites that convert.",
    image: "",
  },
  "Imran Qureshi": {
    name: "Imran Qureshi",
    email: "imran@mentorcraft.com",
    phone: "888-000-1234",
    website: "https://imranexcelpro.com",
    bio: "Excel trainer with 10+ years helping teams become spreadsheet pros.",
    image: "",
  },
  "Nida Khan": {
    name: "Nida Khan",
    email: "nida@mentorcraft.com",
    phone: "909-101-1121",
    website: "https://nidaufx.com",
    bio: "Figma design expert with a minimalist, user-centered design philosophy.",
    image: "",
  },
  "Talha Naeem": {
    name: "Talha Naeem",
    email: "talha@mentorcraft.com",
    phone: "303-505-7070",
    website: "https://talhacreates.com",
    bio: "YouTube creator with a focus on niche channel growth and monetization.",
    image: "",
  },
  "Kiran Fatima": {
    name: "Kiran Fatima",
    email: "kiran@mentorcraft.com",
    phone: "212-343-5656",
    website: "https://kiranjs.dev",
    bio: "Frontend developer and teacher who simplifies JavaScript for all levels.",
    image: "",
  },
  "Bilal Arshad": {
    name: "Bilal Arshad",
    email: "bilal@mentorcraft.com",
    phone: "646-999-0011",
    website: "https://bilalcloud.com",
    bio: "Cloud architect & DevOps engineer who loves teaching AWS and cloud-native workflows.",
    image: "",
  },
  "Maria Asif": {
    name: "Maria Asif",
    email: "maria@mentorcraft.com",
    phone: "505-123-7890",
    website: "https://mariaseo.com",
    bio: "SEO & SEM strategist with a data-driven approach to rankings and ROI.",
    image: "",
  },
  "Hassan Raza": {
    name: "Hassan Raza",
    email: "hassan@mentorcraft.com",
    phone: "303-888-9999",
    website: "https://hassanflutter.com",
    bio: "Flutter app developer bringing beautiful cross-platform apps to life.",
    image: "",
  },
  "Nimra Shah": {
    name: "Nimra Shah",
    email: "nimra@mentorcraft.com",
    phone: "777-888-4444",
    website: "https://nimrashah.com",
    bio: "Public speaking coach helping professionals unlock confident communication.",
    image: "",
  },
};

export default instructorData;
