# Generated by Django 5.2.1 on 2025-08-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_added_at_wishlist_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='wishlist',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='course',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='student',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
