# Generated by Django 5.2.1 on 2025-07-25 17:11

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('discount_price', models.CharField(blank=True, max_length=20)),
                ('duration', models.CharField(max_length=50)),
                ('lessons', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=courses.models.course_image_upload_path)),
                ('instructor', models.CharField(max_length=100)),
                ('instructor_email', models.EmailField(max_length=254)),
                ('rating', models.FloatField(default=4.8)),
                ('students', models.PositiveIntegerField(default=0)),
                ('curriculum_intro', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('faqs', models.JSONField(blank=True, null=True)),
                ('curriculum', models.JSONField(blank=True, null=True)),
                ('videos', models.JSONField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_keywords', models.TextField(blank=True)),
                ('seo_description', models.TextField(blank=True)),
                ('has_expiration', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
