# Generated by Django 5.2.1 on 2025-07-27 21:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_video_file_alter_course_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
