# Generated by Django 5.2.1 on 2025-07-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='course',
            name='seo_title',
        ),
    ]
