# Generated by Django 5.2.1 on 2025-07-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_assignment_lecture_note_quiz_quizquestion_quizoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='order',
        ),
    ]
