# Generated by Django 5.2.1 on 2025-09-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_lecture_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=models.URLField(blank=True, help_text='YouTube embed link or Google Meet link'),
        ),
    ]
