# Generated by Django 5.2.1 on 2025-09-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_lecture_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=models.URLField(blank=True, help_text='Google Meet link'),
        ),
    ]
