# Generated by Django 5.2.1 on 2025-07-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='message',
            new_name='content',
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='publish_immediately',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz')], default='GENERAL', max_length=20),
        ),
    ]
