# Generated by Django 5.2.1 on 2025-07-29 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_seo_description_and_more'),
        ('instructor', '0003_rename_message_announcement_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorCourseAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_earnings', models.JSONField(default=dict)),
                ('enrollments', models.PositiveIntegerField(default=0)),
                ('monthly_enrollments', models.JSONField(default=dict)),
                ('average_quiz_score', models.FloatField(default=0.0)),
                ('quiz_scores', models.JSONField(default=dict)),
                ('rating', models.FloatField(default=0.0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
