# Generated by Django 5.2.1 on 2025-07-29 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_instructorcourseanalytics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorcourseanalytics',
            name='monthly_earnings',
        ),
        migrations.RemoveField(
            model_name='instructorcourseanalytics',
            name='monthly_enrollments',
        ),
        migrations.RemoveField(
            model_name='instructorcourseanalytics',
            name='quiz_scores',
        ),
        migrations.CreateModel(
            name='MonthlyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('enrollments', models.PositiveIntegerField(default=0)),
                ('quiz_scores', models.JSONField(default=list)),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_data', to='instructor.instructorcourseanalytics')),
            ],
            options={
                'unique_together': {('analytics', 'month', 'year')},
            },
        ),
    ]
